export const data = [{
  "id": 1,
  "first_name": "Bellina",
  "last_name": "Moncey",
  "email": "bmoncey0@nifty.com",
  "gender": "Bigender",
  "ip_address": "64.75.95.247",
  "computer_name": "Desktop",
  "operating_system": "Windows",
  "processor": "Intel Core i5",
  "ram": 53,
  "storage_capacity": 1980,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "AA-5B-7C-A8-6E-47",
  "antivirus": "Norton",
  "firewall_enabled": false,
  "ssn": "584-16-6550"
}, {
  "id": 2,
  "first_name": "Suellen",
  "last_name": "Yeldon",
  "email": "syeldon1@yahoo.co.jp",
  "gender": "Female",
  "ip_address": "82.168.126.30",
  "computer_name": "Server",
  "operating_system": "Windows",
  "processor": "AMD Ryzen 7",
  "ram": 50,
  "storage_capacity": 785,
  "graphics_card": "Intel Iris Xe",
  "mac_address": "D1-48-38-4B-74-7A",
  "antivirus": "McAfee",
  "firewall_enabled": true,
  "ssn": "331-93-4682"
}, {
  "id": 3,
  "first_name": "Rhett",
  "last_name": "Mendenhall",
  "email": "rmendenhall2@elpais.com",
  "gender": "Male",
  "ip_address": "132.250.255.54",
  "computer_name": "Server",
  "operating_system": "Windows",
  "processor": "Qualcomm Snapdragon",
  "ram": 5,
  "storage_capacity": 4084,
  "graphics_card": "Intel Iris Xe",
  "mac_address": "31-A1-EF-61-16-6D",
  "antivirus": "Windows Defender",
  "firewall_enabled": true,
  "ssn": "172-87-5207"
}, {
  "id": 4,
  "first_name": "Obadias",
  "last_name": "Brightman",
  "email": "obrightman3@uol.com.br",
  "gender": "Male",
  "ip_address": "183.79.76.232",
  "computer_name": "Desktop",
  "operating_system": "Linux",
  "processor": "Qualcomm Snapdragon",
  "ram": 27,
  "storage_capacity": 3603,
  "graphics_card": "Intel Iris Xe",
  "mac_address": "27-D7-D9-7C-55-FA",
  "antivirus": "Windows Defender",
  "firewall_enabled": false,
  "ssn": "621-96-5425"
}, {
  "id": 5,
  "first_name": "Betteann",
  "last_name": "Woonton",
  "email": "bwoonton4@privacy.gov.au",
  "gender": "Female",
  "ip_address": "200.20.38.26",
  "computer_name": "Laptop",
  "operating_system": "Linux",
  "processor": "AMD Ryzen 7",
  "ram": 44,
  "storage_capacity": 3728,
  "graphics_card": "NVIDIA GeForce RTX 3080",
  "mac_address": "73-09-60-54-FF-74",
  "antivirus": "McAfee",
  "firewall_enabled": true,
  "ssn": "689-90-5580"
}, {
  "id": 6,
  "first_name": "Kelsey",
  "last_name": "Davidove",
  "email": "kdavidove5@eepurl.com",
  "gender": "Bigender",
  "ip_address": "46.200.163.172",
  "computer_name": "Laptop",
  "operating_system": "macOS",
  "processor": "AMD Ryzen 7",
  "ram": 53,
  "storage_capacity": 897,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "42-AB-4E-A6-8A-07",
  "antivirus": "McAfee",
  "firewall_enabled": false,
  "ssn": "128-19-6041"
}, {
  "id": 7,
  "first_name": "Sam",
  "last_name": "Curling",
  "email": "scurling6@lulu.com",
  "gender": "Male",
  "ip_address": "113.156.76.0",
  "computer_name": "Desktop",
  "operating_system": "Linux",
  "processor": "Intel Core i5",
  "ram": 5,
  "storage_capacity": 639,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "C8-30-26-7E-9E-9E",
  "antivirus": "Norton",
  "firewall_enabled": false,
  "ssn": "478-58-5737"
}, {
  "id": 8,
  "first_name": "Ruthe",
  "last_name": "Fray",
  "email": "rfray7@upenn.edu",
  "gender": "Female",
  "ip_address": "70.126.33.20",
  "computer_name": "Laptop",
  "operating_system": "Windows",
  "processor": "AMD Ryzen 7",
  "ram": 54,
  "storage_capacity": 1985,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "BE-31-3D-EB-B9-51",
  "antivirus": "McAfee",
  "firewall_enabled": true,
  "ssn": "772-09-1666"
}, {
  "id": 9,
  "first_name": "Nanni",
  "last_name": "Robinette",
  "email": "nrobinette8@oracle.com",
  "gender": "Female",
  "ip_address": "60.120.186.143",
  "computer_name": "Server",
  "operating_system": "macOS",
  "processor": "Qualcomm Snapdragon",
  "ram": 57,
  "storage_capacity": 3666,
  "graphics_card": "NVIDIA GeForce RTX 3080",
  "mac_address": "43-33-33-24-C6-4D",
  "antivirus": "Windows Defender",
  "firewall_enabled": false,
  "ssn": "820-31-3612"
}, {
  "id": 10,
  "first_name": "Leela",
  "last_name": "Rich",
  "email": "lrich9@bluehost.com",
  "gender": "Female",
  "ip_address": "161.10.62.124",
  "computer_name": "Server",
  "operating_system": "Windows",
  "processor": "Intel Core i5",
  "ram": 12,
  "storage_capacity": 910,
  "graphics_card": "Intel Iris Xe",
  "mac_address": "05-B5-5C-6F-47-FD",
  "antivirus": "McAfee",
  "firewall_enabled": true,
  "ssn": "131-04-5764"
}, {
  "id": 11,
  "first_name": "Brendan",
  "last_name": "Fidoe",
  "email": "bfidoea@pcworld.com",
  "gender": "Male",
  "ip_address": "223.144.135.213",
  "computer_name": "Laptop",
  "operating_system": "Windows",
  "processor": "AMD Ryzen 7",
  "ram": 8,
  "storage_capacity": 922,
  "graphics_card": "NVIDIA GeForce RTX 3080",
  "mac_address": "AE-A6-CD-25-4E-9A",
  "antivirus": "Windows Defender",
  "firewall_enabled": true,
  "ssn": "421-19-9026"
}, {
  "id": 12,
  "first_name": "Bryn",
  "last_name": "Reisen",
  "email": "breisenb@dailymotion.com",
  "gender": "Female",
  "ip_address": "209.241.190.51",
  "computer_name": "Desktop",
  "operating_system": "Linux",
  "processor": "AMD Ryzen 7",
  "ram": 40,
  "storage_capacity": 1270,
  "graphics_card": "NVIDIA GeForce RTX 3080",
  "mac_address": "5A-14-3C-77-24-53",
  "antivirus": "Windows Defender",
  "firewall_enabled": true,
  "ssn": "737-87-8952"
}, {
  "id": 13,
  "first_name": "Amos",
  "last_name": "Barca",
  "email": "abarcac@cnet.com",
  "gender": "Male",
  "ip_address": "50.115.83.68",
  "computer_name": "Server",
  "operating_system": "macOS",
  "processor": "Intel Core i5",
  "ram": 50,
  "storage_capacity": 3830,
  "graphics_card": "Intel Iris Xe",
  "mac_address": "F9-41-F1-61-EF-E6",
  "antivirus": "Norton",
  "firewall_enabled": true,
  "ssn": "872-49-0352"
}, {
  "id": 14,
  "first_name": "Gardener",
  "last_name": "Gammie",
  "email": "ggammied@icio.us",
  "gender": "Male",
  "ip_address": "130.83.37.180",
  "computer_name": "Server",
  "operating_system": "Windows",
  "processor": "Intel Core i5",
  "ram": 34,
  "storage_capacity": 897,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "BA-32-A8-9E-33-93",
  "antivirus": "Norton",
  "firewall_enabled": false,
  "ssn": "735-09-7254"
}, {
  "id": 15,
  "first_name": "Angelo",
  "last_name": "Dolligon",
  "email": "adolligone@storify.com",
  "gender": "Non-binary",
  "ip_address": "10.147.213.224",
  "computer_name": "Server",
  "operating_system": "Linux",
  "processor": "Intel Core i5",
  "ram": 37,
  "storage_capacity": 1293,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "5A-66-DB-FB-68-BE",
  "antivirus": "Norton",
  "firewall_enabled": false,
  "ssn": "495-60-5600"
}, {
  "id": 16,
  "first_name": "Kristofer",
  "last_name": "Seaking",
  "email": "kseakingf@simplemachines.org",
  "gender": "Male",
  "ip_address": "57.254.19.186",
  "computer_name": "Desktop",
  "operating_system": "Windows",
  "processor": "Intel Core i5",
  "ram": 52,
  "storage_capacity": 1556,
  "graphics_card": "NVIDIA GeForce RTX 3080",
  "mac_address": "6D-B9-AA-2B-C4-3A",
  "antivirus": "McAfee",
  "firewall_enabled": true,
  "ssn": "619-72-7063"
}, {
  "id": 17,
  "first_name": "Rufus",
  "last_name": "Phippen",
  "email": "rphippeng@hibu.com",
  "gender": "Male",
  "ip_address": "95.105.188.147",
  "computer_name": "Server",
  "operating_system": "Windows",
  "processor": "Qualcomm Snapdragon",
  "ram": 6,
  "storage_capacity": 959,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "E6-90-7F-D1-78-6F",
  "antivirus": "McAfee",
  "firewall_enabled": true,
  "ssn": "486-09-1522"
}, {
  "id": 18,
  "first_name": "Dwight",
  "last_name": "Rishbrook",
  "email": "drishbrookh@discuz.net",
  "gender": "Genderqueer",
  "ip_address": "104.22.52.15",
  "computer_name": "Laptop",
  "operating_system": "Linux",
  "processor": "AMD Ryzen 7",
  "ram": 18,
  "storage_capacity": 3262,
  "graphics_card": "Intel Iris Xe",
  "mac_address": "A0-9B-D3-30-72-31",
  "antivirus": "McAfee",
  "firewall_enabled": false,
  "ssn": "570-39-3900"
}, {
  "id": 19,
  "first_name": "Gareth",
  "last_name": "Brushneen",
  "email": "gbrushneeni@ucoz.com",
  "gender": "Male",
  "ip_address": "121.30.3.89",
  "computer_name": "Server",
  "operating_system": "macOS",
  "processor": "Qualcomm Snapdragon",
  "ram": 23,
  "storage_capacity": 1718,
  "graphics_card": "NVIDIA GeForce RTX 3080",
  "mac_address": "80-45-63-A9-5B-91",
  "antivirus": "Windows Defender",
  "firewall_enabled": false,
  "ssn": "767-12-6842"
}, {
  "id": 20,
  "first_name": "Dur",
  "last_name": "Dunks",
  "email": "ddunksj@twitter.com",
  "gender": "Male",
  "ip_address": "200.166.150.131",
  "computer_name": "Laptop",
  "operating_system": "macOS",
  "processor": "AMD Ryzen 7",
  "ram": 61,
  "storage_capacity": 1963,
  "graphics_card": "Intel Iris Xe",
  "mac_address": "AE-F7-C0-2B-05-40",
  "antivirus": "McAfee",
  "firewall_enabled": false,
  "ssn": "349-47-0239"
}, {
  "id": 21,
  "first_name": "Leigha",
  "last_name": "Kerwen",
  "email": "lkerwenk@gizmodo.com",
  "gender": "Female",
  "ip_address": "36.234.22.192",
  "computer_name": "Laptop",
  "operating_system": "macOS",
  "processor": "AMD Ryzen 7",
  "ram": 15,
  "storage_capacity": 3802,
  "graphics_card": "NVIDIA GeForce RTX 3080",
  "mac_address": "F6-CF-87-16-2E-2D",
  "antivirus": "Norton",
  "firewall_enabled": false,
  "ssn": "475-03-7787"
}, {
  "id": 22,
  "first_name": "Biron",
  "last_name": "Saulter",
  "email": "bsaulterl@who.int",
  "gender": "Male",
  "ip_address": "145.68.186.134",
  "computer_name": "Laptop",
  "operating_system": "Linux",
  "processor": "AMD Ryzen 7",
  "ram": 27,
  "storage_capacity": 2601,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "4E-81-DF-CB-33-80",
  "antivirus": "Windows Defender",
  "firewall_enabled": true,
  "ssn": "187-51-1307"
}, {
  "id": 23,
  "first_name": "Sharline",
  "last_name": "Humphery",
  "email": "shumpherym@sciencedirect.com",
  "gender": "Female",
  "ip_address": "67.12.148.19",
  "computer_name": "Server",
  "operating_system": "Windows",
  "processor": "Qualcomm Snapdragon",
  "ram": 47,
  "storage_capacity": 2744,
  "graphics_card": "Intel Iris Xe",
  "mac_address": "F4-E5-07-C9-7B-B0",
  "antivirus": "Norton",
  "firewall_enabled": false,
  "ssn": "555-06-9587"
}, {
  "id": 24,
  "first_name": "Clem",
  "last_name": "MacKenny",
  "email": "cmackennyn@pcworld.com",
  "gender": "Male",
  "ip_address": "171.113.93.132",
  "computer_name": "Laptop",
  "operating_system": "Windows",
  "processor": "AMD Ryzen 7",
  "ram": 23,
  "storage_capacity": 3531,
  "graphics_card": "NVIDIA GeForce RTX 3080",
  "mac_address": "91-A0-A9-0C-DB-39",
  "antivirus": "Windows Defender",
  "firewall_enabled": false,
  "ssn": "765-32-6615"
}, {
  "id": 25,
  "first_name": "Sadie",
  "last_name": "McKenny",
  "email": "smckennyo@amazonaws.com",
  "gender": "Female",
  "ip_address": "82.26.175.161",
  "computer_name": "Server",
  "operating_system": "macOS",
  "processor": "Intel Core i5",
  "ram": 8,
  "storage_capacity": 273,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "CE-AB-60-25-98-E1",
  "antivirus": "Windows Defender",
  "firewall_enabled": true,
  "ssn": "180-94-9998"
}, {
  "id": 26,
  "first_name": "Bron",
  "last_name": "Bockh",
  "email": "bbockhp@admin.ch",
  "gender": "Male",
  "ip_address": "94.39.149.220",
  "computer_name": "Desktop",
  "operating_system": "macOS",
  "processor": "Intel Core i5",
  "ram": 48,
  "storage_capacity": 912,
  "graphics_card": "Intel Iris Xe",
  "mac_address": "63-11-C2-E4-8D-11",
  "antivirus": "Norton",
  "firewall_enabled": true,
  "ssn": "614-35-3438"
}, {
  "id": 27,
  "first_name": "Martainn",
  "last_name": "Borsi",
  "email": "mborsiq@state.gov",
  "gender": "Male",
  "ip_address": "143.123.32.127",
  "computer_name": "Server",
  "operating_system": "Windows",
  "processor": "Qualcomm Snapdragon",
  "ram": 20,
  "storage_capacity": 3080,
  "graphics_card": "Intel Iris Xe",
  "mac_address": "CE-A0-87-CA-B2-02",
  "antivirus": "Windows Defender",
  "firewall_enabled": true,
  "ssn": "711-23-6984"
}, {
  "id": 28,
  "first_name": "Lizette",
  "last_name": "Ambrose",
  "email": "lambroser@nih.gov",
  "gender": "Female",
  "ip_address": "111.63.100.176",
  "computer_name": "Laptop",
  "operating_system": "macOS",
  "processor": "Intel Core i5",
  "ram": 31,
  "storage_capacity": 1795,
  "graphics_card": "Intel Iris Xe",
  "mac_address": "E7-A2-C3-A6-92-B8",
  "antivirus": "McAfee",
  "firewall_enabled": true,
  "ssn": "109-11-3764"
}, {
  "id": 29,
  "first_name": "Iris",
  "last_name": "Southan",
  "email": "isouthans@loc.gov",
  "gender": "Female",
  "ip_address": "73.49.35.165",
  "computer_name": "Desktop",
  "operating_system": "Windows",
  "processor": "Intel Core i5",
  "ram": 22,
  "storage_capacity": 1721,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "77-87-12-46-46-32",
  "antivirus": "McAfee",
  "firewall_enabled": true,
  "ssn": "325-08-4612"
}, {
  "id": 30,
  "first_name": "Sammie",
  "last_name": "Causley",
  "email": "scausleyt@cyberchimps.com",
  "gender": "Male",
  "ip_address": "139.32.183.15",
  "computer_name": "Laptop",
  "operating_system": "macOS",
  "processor": "AMD Ryzen 7",
  "ram": 56,
  "storage_capacity": 2804,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "6A-5E-EB-90-A5-98",
  "antivirus": "Windows Defender",
  "firewall_enabled": false,
  "ssn": "239-99-6518"
}, {
  "id": 31,
  "first_name": "Bren",
  "last_name": "Dighton",
  "email": "bdightonu@google.pl",
  "gender": "Female",
  "ip_address": "87.203.235.49",
  "computer_name": "Laptop",
  "operating_system": "Windows",
  "processor": "AMD Ryzen 7",
  "ram": 46,
  "storage_capacity": 1420,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "AF-B4-26-4F-1E-10",
  "antivirus": "Norton",
  "firewall_enabled": false,
  "ssn": "285-85-2309"
}, {
  "id": 32,
  "first_name": "Kippar",
  "last_name": "Britto",
  "email": "kbrittov@marriott.com",
  "gender": "Male",
  "ip_address": "190.98.80.128",
  "computer_name": "Laptop",
  "operating_system": "Linux",
  "processor": "AMD Ryzen 7",
  "ram": 35,
  "storage_capacity": 3445,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "CD-20-20-0C-E7-58",
  "antivirus": "McAfee",
  "firewall_enabled": true,
  "ssn": "487-53-7661"
}, {
  "id": 33,
  "first_name": "Jeremias",
  "last_name": "Nobbs",
  "email": "jnobbsw@blog.com",
  "gender": "Male",
  "ip_address": "169.115.169.56",
  "computer_name": "Server",
  "operating_system": "Windows",
  "processor": "Intel Core i5",
  "ram": 50,
  "storage_capacity": 1941,
  "graphics_card": "NVIDIA GeForce RTX 3080",
  "mac_address": "89-62-30-22-BA-EE",
  "antivirus": "Windows Defender",
  "firewall_enabled": false,
  "ssn": "603-37-2494"
}, {
  "id": 34,
  "first_name": "Karlens",
  "last_name": "Nelissen",
  "email": "knelissenx@sourceforge.net",
  "gender": "Male",
  "ip_address": "42.150.64.160",
  "computer_name": "Server",
  "operating_system": "Windows",
  "processor": "Intel Core i5",
  "ram": 53,
  "storage_capacity": 4074,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "05-5E-B8-9F-23-8E",
  "antivirus": "Norton",
  "firewall_enabled": false,
  "ssn": "108-90-6576"
}, {
  "id": 35,
  "first_name": "Keeley",
  "last_name": "Waleran",
  "email": "kwalerany@cocolog-nifty.com",
  "gender": "Female",
  "ip_address": "115.95.188.26",
  "computer_name": "Desktop",
  "operating_system": "Windows",
  "processor": "Intel Core i5",
  "ram": 13,
  "storage_capacity": 2167,
  "graphics_card": "Intel Iris Xe",
  "mac_address": "36-46-34-FC-C3-19",
  "antivirus": "Norton",
  "firewall_enabled": true,
  "ssn": "798-06-1871"
}, {
  "id": 36,
  "first_name": "Dorey",
  "last_name": "Ullrich",
  "email": "dullrichz@npr.org",
  "gender": "Female",
  "ip_address": "183.253.35.117",
  "computer_name": "Desktop",
  "operating_system": "Windows",
  "processor": "AMD Ryzen 7",
  "ram": 12,
  "storage_capacity": 3046,
  "graphics_card": "NVIDIA GeForce RTX 3080",
  "mac_address": "4F-E9-88-1F-29-C4",
  "antivirus": "Windows Defender",
  "firewall_enabled": true,
  "ssn": "637-36-1384"
}, {
  "id": 37,
  "first_name": "Jean",
  "last_name": "Mowle",
  "email": "jmowle10@ebay.com",
  "gender": "Male",
  "ip_address": "158.51.175.155",
  "computer_name": "Laptop",
  "operating_system": "macOS",
  "processor": "Intel Core i5",
  "ram": 7,
  "storage_capacity": 3889,
  "graphics_card": "NVIDIA GeForce RTX 3080",
  "mac_address": "D5-A6-30-53-AE-29",
  "antivirus": "McAfee",
  "firewall_enabled": false,
  "ssn": "204-92-6546"
}, {
  "id": 38,
  "first_name": "Shandra",
  "last_name": "Bellinger",
  "email": "sbellinger11@typepad.com",
  "gender": "Genderfluid",
  "ip_address": "138.135.161.227",
  "computer_name": "Desktop",
  "operating_system": "macOS",
  "processor": "Intel Core i5",
  "ram": 48,
  "storage_capacity": 913,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "EB-91-B1-E0-87-F3",
  "antivirus": "McAfee",
  "firewall_enabled": true,
  "ssn": "583-46-7178"
}, {
  "id": 39,
  "first_name": "Marlena",
  "last_name": "Matei",
  "email": "mmatei12@bigcartel.com",
  "gender": "Female",
  "ip_address": "57.255.242.119",
  "computer_name": "Server",
  "operating_system": "macOS",
  "processor": "Qualcomm Snapdragon",
  "ram": 16,
  "storage_capacity": 2237,
  "graphics_card": "Intel Iris Xe",
  "mac_address": "88-31-AC-50-99-20",
  "antivirus": "McAfee",
  "firewall_enabled": false,
  "ssn": "362-98-8036"
}, {
  "id": 40,
  "first_name": "Arlette",
  "last_name": "Swale",
  "email": "aswale13@quantcast.com",
  "gender": "Female",
  "ip_address": "221.138.43.125",
  "computer_name": "Desktop",
  "operating_system": "Linux",
  "processor": "Intel Core i5",
  "ram": 47,
  "storage_capacity": 2014,
  "graphics_card": "NVIDIA GeForce RTX 3080",
  "mac_address": "1A-A3-04-94-85-50",
  "antivirus": "Norton",
  "firewall_enabled": false,
  "ssn": "700-71-2201"
}, {
  "id": 41,
  "first_name": "Ange",
  "last_name": "Hendin",
  "email": "ahendin14@photobucket.com",
  "gender": "Female",
  "ip_address": "156.96.177.243",
  "computer_name": "Server",
  "operating_system": "macOS",
  "processor": "Qualcomm Snapdragon",
  "ram": 22,
  "storage_capacity": 2315,
  "graphics_card": "Intel Iris Xe",
  "mac_address": "BE-AF-03-B0-5D-99",
  "antivirus": "Norton",
  "firewall_enabled": true,
  "ssn": "266-62-7386"
}, {
  "id": 42,
  "first_name": "Gasper",
  "last_name": "Deverson",
  "email": "gdeverson15@telegraph.co.uk",
  "gender": "Male",
  "ip_address": "222.229.191.74",
  "computer_name": "Desktop",
  "operating_system": "macOS",
  "processor": "Intel Core i5",
  "ram": 11,
  "storage_capacity": 731,
  "graphics_card": "NVIDIA GeForce RTX 3080",
  "mac_address": "3F-DC-E5-A0-B6-B3",
  "antivirus": "Windows Defender",
  "firewall_enabled": true,
  "ssn": "122-35-9020"
}, {
  "id": 43,
  "first_name": "Giovanna",
  "last_name": "Lemmanbie",
  "email": "glemmanbie16@123-reg.co.uk",
  "gender": "Female",
  "ip_address": "72.48.38.50",
  "computer_name": "Laptop",
  "operating_system": "macOS",
  "processor": "Qualcomm Snapdragon",
  "ram": 21,
  "storage_capacity": 2596,
  "graphics_card": "NVIDIA GeForce RTX 3080",
  "mac_address": "F6-AF-4D-38-55-C6",
  "antivirus": "Windows Defender",
  "firewall_enabled": true,
  "ssn": "873-32-8103"
}, {
  "id": 44,
  "first_name": "Lorain",
  "last_name": "Fenney",
  "email": "lfenney17@vimeo.com",
  "gender": "Female",
  "ip_address": "63.177.205.36",
  "computer_name": "Server",
  "operating_system": "Linux",
  "processor": "Intel Core i5",
  "ram": 20,
  "storage_capacity": 989,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "AB-F8-EC-F6-2C-87",
  "antivirus": "McAfee",
  "firewall_enabled": true,
  "ssn": "526-24-6870"
}, {
  "id": 45,
  "first_name": "Peder",
  "last_name": "Surmeyers",
  "email": "psurmeyers18@smugmug.com",
  "gender": "Male",
  "ip_address": "23.116.116.156",
  "computer_name": "Server",
  "operating_system": "macOS",
  "processor": "Qualcomm Snapdragon",
  "ram": 55,
  "storage_capacity": 180,
  "graphics_card": "NVIDIA GeForce RTX 3080",
  "mac_address": "09-95-14-7F-C7-B4",
  "antivirus": "Norton",
  "firewall_enabled": true,
  "ssn": "676-09-3152"
}, {
  "id": 46,
  "first_name": "Daune",
  "last_name": "Lifton",
  "email": "dlifton19@pbs.org",
  "gender": "Bigender",
  "ip_address": "254.108.30.49",
  "computer_name": "Laptop",
  "operating_system": "Linux",
  "processor": "Qualcomm Snapdragon",
  "ram": 38,
  "storage_capacity": 3083,
  "graphics_card": "Intel Iris Xe",
  "mac_address": "92-1C-AB-57-4B-DF",
  "antivirus": "Windows Defender",
  "firewall_enabled": false,
  "ssn": "639-98-5931"
}, {
  "id": 47,
  "first_name": "Shadow",
  "last_name": "Hadlington",
  "email": "shadlington1a@nyu.edu",
  "gender": "Male",
  "ip_address": "20.137.119.177",
  "computer_name": "Server",
  "operating_system": "Windows",
  "processor": "Qualcomm Snapdragon",
  "ram": 19,
  "storage_capacity": 3701,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "91-CF-36-E8-01-2C",
  "antivirus": "McAfee",
  "firewall_enabled": false,
  "ssn": "825-68-5849"
}, {
  "id": 48,
  "first_name": "Frederik",
  "last_name": "Gonnel",
  "email": "fgonnel1b@unblog.fr",
  "gender": "Male",
  "ip_address": "251.206.68.115",
  "computer_name": "Desktop",
  "operating_system": "macOS",
  "processor": "AMD Ryzen 7",
  "ram": 10,
  "storage_capacity": 709,
  "graphics_card": "Intel Iris Xe",
  "mac_address": "2F-21-DD-71-E9-E1",
  "antivirus": "Norton",
  "firewall_enabled": false,
  "ssn": "885-82-5134"
}, {
  "id": 49,
  "first_name": "Georgena",
  "last_name": "Goodinge",
  "email": "ggoodinge1c@chicagotribune.com",
  "gender": "Female",
  "ip_address": "209.239.122.151",
  "computer_name": "Desktop",
  "operating_system": "Windows",
  "processor": "Qualcomm Snapdragon",
  "ram": 47,
  "storage_capacity": 2341,
  "graphics_card": "Intel Iris Xe",
  "mac_address": "BC-46-77-22-0E-7A",
  "antivirus": "Norton",
  "firewall_enabled": true,
  "ssn": "867-67-7631"
}, {
  "id": 50,
  "first_name": "Mark",
  "last_name": "Pactat",
  "email": "mpactat1d@amazon.co.jp",
  "gender": "Male",
  "ip_address": "0.47.87.11",
  "computer_name": "Laptop",
  "operating_system": "Linux",
  "processor": "Qualcomm Snapdragon",
  "ram": 18,
  "storage_capacity": 3486,
  "graphics_card": "NVIDIA GeForce RTX 3080",
  "mac_address": "75-4C-DE-2E-25-71",
  "antivirus": "Windows Defender",
  "firewall_enabled": true,
  "ssn": "208-82-1656"
}, {
  "id": 51,
  "first_name": "Verge",
  "last_name": "Koopman",
  "email": "vkoopman1e@wired.com",
  "gender": "Male",
  "ip_address": "156.204.185.230",
  "computer_name": "Server",
  "operating_system": "Linux",
  "processor": "AMD Ryzen 7",
  "ram": 35,
  "storage_capacity": 1776,
  "graphics_card": "Intel Iris Xe",
  "mac_address": "24-A3-A9-1F-1B-8F",
  "antivirus": "McAfee",
  "firewall_enabled": false,
  "ssn": "883-83-3548"
}, {
  "id": 52,
  "first_name": "Merle",
  "last_name": "Walewski",
  "email": "mwalewski1f@storify.com",
  "gender": "Male",
  "ip_address": "181.188.72.248",
  "computer_name": "Server",
  "operating_system": "Linux",
  "processor": "Qualcomm Snapdragon",
  "ram": 14,
  "storage_capacity": 2785,
  "graphics_card": "NVIDIA GeForce RTX 3080",
  "mac_address": "66-AE-33-27-77-A0",
  "antivirus": "Windows Defender",
  "firewall_enabled": false,
  "ssn": "608-83-0512"
}, {
  "id": 53,
  "first_name": "Hayden",
  "last_name": "Hairs",
  "email": "hhairs1g@wufoo.com",
  "gender": "Male",
  "ip_address": "255.36.80.202",
  "computer_name": "Laptop",
  "operating_system": "macOS",
  "processor": "Intel Core i5",
  "ram": 60,
  "storage_capacity": 1662,
  "graphics_card": "NVIDIA GeForce RTX 3080",
  "mac_address": "AA-68-45-B7-50-11",
  "antivirus": "Norton",
  "firewall_enabled": false,
  "ssn": "865-36-5106"
}, {
  "id": 54,
  "first_name": "Dredi",
  "last_name": "Skelly",
  "email": "dskelly1h@google.nl",
  "gender": "Female",
  "ip_address": "205.108.136.175",
  "computer_name": "Server",
  "operating_system": "macOS",
  "processor": "Qualcomm Snapdragon",
  "ram": 12,
  "storage_capacity": 1249,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "CA-7F-16-94-F5-DF",
  "antivirus": "Windows Defender",
  "firewall_enabled": false,
  "ssn": "767-58-4360"
}, {
  "id": 55,
  "first_name": "Farra",
  "last_name": "Ledamun",
  "email": "fledamun1i@twitpic.com",
  "gender": "Female",
  "ip_address": "235.29.205.242",
  "computer_name": "Server",
  "operating_system": "Linux",
  "processor": "Qualcomm Snapdragon",
  "ram": 41,
  "storage_capacity": 2155,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "04-0B-74-64-E5-19",
  "antivirus": "Windows Defender",
  "firewall_enabled": false,
  "ssn": "122-09-1172"
}, {
  "id": 56,
  "first_name": "Fair",
  "last_name": "McGirr",
  "email": "fmcgirr1j@amazon.co.jp",
  "gender": "Agender",
  "ip_address": "42.155.182.166",
  "computer_name": "Desktop",
  "operating_system": "Windows",
  "processor": "Intel Core i5",
  "ram": 36,
  "storage_capacity": 847,
  "graphics_card": "NVIDIA GeForce RTX 3080",
  "mac_address": "32-98-2C-B2-A5-2C",
  "antivirus": "Windows Defender",
  "firewall_enabled": true,
  "ssn": "678-41-7938"
}, {
  "id": 57,
  "first_name": "Yevette",
  "last_name": "Angrick",
  "email": "yangrick1k@biglobe.ne.jp",
  "gender": "Female",
  "ip_address": "32.206.88.55",
  "computer_name": "Laptop",
  "operating_system": "Windows",
  "processor": "AMD Ryzen 7",
  "ram": 32,
  "storage_capacity": 1833,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "27-2E-F8-F0-6B-4D",
  "antivirus": "Norton",
  "firewall_enabled": true,
  "ssn": "263-14-4379"
}, {
  "id": 58,
  "first_name": "Thalia",
  "last_name": "Giriardelli",
  "email": "tgiriardelli1l@nydailynews.com",
  "gender": "Female",
  "ip_address": "62.19.216.33",
  "computer_name": "Desktop",
  "operating_system": "Linux",
  "processor": "AMD Ryzen 7",
  "ram": 12,
  "storage_capacity": 1320,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "11-01-E8-71-88-0C",
  "antivirus": "McAfee",
  "firewall_enabled": false,
  "ssn": "464-88-5558"
}, {
  "id": 59,
  "first_name": "Mame",
  "last_name": "Dannett",
  "email": "mdannett1m@ted.com",
  "gender": "Female",
  "ip_address": "185.102.77.190",
  "computer_name": "Desktop",
  "operating_system": "macOS",
  "processor": "Qualcomm Snapdragon",
  "ram": 9,
  "storage_capacity": 3207,
  "graphics_card": "Intel Iris Xe",
  "mac_address": "E7-E5-C5-B5-AC-A7",
  "antivirus": "Windows Defender",
  "firewall_enabled": true,
  "ssn": "661-84-3023"
}, {
  "id": 60,
  "first_name": "Faina",
  "last_name": "Fishlock",
  "email": "ffishlock1n@mit.edu",
  "gender": "Female",
  "ip_address": "185.35.74.83",
  "computer_name": "Server",
  "operating_system": "Linux",
  "processor": "Intel Core i5",
  "ram": 33,
  "storage_capacity": 1565,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "E5-35-54-A8-4D-7D",
  "antivirus": "McAfee",
  "firewall_enabled": true,
  "ssn": "127-28-0889"
}, {
  "id": 61,
  "first_name": "Muffin",
  "last_name": "Kemster",
  "email": "mkemster1o@nih.gov",
  "gender": "Female",
  "ip_address": "51.71.72.49",
  "computer_name": "Server",
  "operating_system": "Windows",
  "processor": "Qualcomm Snapdragon",
  "ram": 55,
  "storage_capacity": 3980,
  "graphics_card": "NVIDIA GeForce RTX 3080",
  "mac_address": "BB-7B-1D-DB-F7-96",
  "antivirus": "Windows Defender",
  "firewall_enabled": true,
  "ssn": "466-15-6270"
}, {
  "id": 62,
  "first_name": "Leshia",
  "last_name": "Minger",
  "email": "lminger1p@ning.com",
  "gender": "Female",
  "ip_address": "180.134.115.212",
  "computer_name": "Desktop",
  "operating_system": "Linux",
  "processor": "Qualcomm Snapdragon",
  "ram": 46,
  "storage_capacity": 2296,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "D0-36-82-42-88-2D",
  "antivirus": "McAfee",
  "firewall_enabled": true,
  "ssn": "186-09-9032"
}, {
  "id": 63,
  "first_name": "Deeann",
  "last_name": "Hub",
  "email": "dhub1q@huffingtonpost.com",
  "gender": "Female",
  "ip_address": "159.73.117.189",
  "computer_name": "Laptop",
  "operating_system": "Linux",
  "processor": "Intel Core i5",
  "ram": 17,
  "storage_capacity": 2425,
  "graphics_card": "Intel Iris Xe",
  "mac_address": "C6-EF-15-8B-01-A3",
  "antivirus": "Norton",
  "firewall_enabled": false,
  "ssn": "787-32-0457"
}, {
  "id": 64,
  "first_name": "Norbert",
  "last_name": "Godsil",
  "email": "ngodsil1r@ehow.com",
  "gender": "Polygender",
  "ip_address": "78.219.191.235",
  "computer_name": "Laptop",
  "operating_system": "macOS",
  "processor": "Qualcomm Snapdragon",
  "ram": 35,
  "storage_capacity": 852,
  "graphics_card": "NVIDIA GeForce RTX 3080",
  "mac_address": "45-40-96-29-B1-C7",
  "antivirus": "Norton",
  "firewall_enabled": false,
  "ssn": "832-76-1141"
}, {
  "id": 65,
  "first_name": "Cullie",
  "last_name": "Seligson",
  "email": "cseligson1s@cpanel.net",
  "gender": "Male",
  "ip_address": "171.89.126.58",
  "computer_name": "Laptop",
  "operating_system": "Windows",
  "processor": "Intel Core i5",
  "ram": 26,
  "storage_capacity": 550,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "38-DD-CE-37-31-E1",
  "antivirus": "Norton",
  "firewall_enabled": false,
  "ssn": "256-08-7260"
}, {
  "id": 66,
  "first_name": "Katrinka",
  "last_name": "Wilstead",
  "email": "kwilstead1t@youku.com",
  "gender": "Female",
  "ip_address": "138.218.222.56",
  "computer_name": "Laptop",
  "operating_system": "Windows",
  "processor": "Intel Core i5",
  "ram": 44,
  "storage_capacity": 2576,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "3D-33-E4-52-A6-6D",
  "antivirus": "Norton",
  "firewall_enabled": false,
  "ssn": "590-32-7627"
}, {
  "id": 67,
  "first_name": "Arch",
  "last_name": "Haw",
  "email": "ahaw1u@biblegateway.com",
  "gender": "Male",
  "ip_address": "247.255.235.71",
  "computer_name": "Server",
  "operating_system": "macOS",
  "processor": "AMD Ryzen 7",
  "ram": 14,
  "storage_capacity": 4089,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "87-AD-40-4B-27-90",
  "antivirus": "Windows Defender",
  "firewall_enabled": false,
  "ssn": "342-03-0550"
}, {
  "id": 68,
  "first_name": "Langston",
  "last_name": "Trudgion",
  "email": "ltrudgion1v@hubpages.com",
  "gender": "Male",
  "ip_address": "27.155.108.94",
  "computer_name": "Laptop",
  "operating_system": "Windows",
  "processor": "AMD Ryzen 7",
  "ram": 43,
  "storage_capacity": 648,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "02-B6-CE-F0-2F-CD",
  "antivirus": "Norton",
  "firewall_enabled": true,
  "ssn": "222-26-0831"
}, {
  "id": 69,
  "first_name": "Sigismundo",
  "last_name": "Pemble",
  "email": "spemble1w@sciencedaily.com",
  "gender": "Male",
  "ip_address": "112.12.47.143",
  "computer_name": "Laptop",
  "operating_system": "Linux",
  "processor": "Qualcomm Snapdragon",
  "ram": 61,
  "storage_capacity": 3607,
  "graphics_card": "Intel Iris Xe",
  "mac_address": "25-6B-A8-88-47-E7",
  "antivirus": "McAfee",
  "firewall_enabled": true,
  "ssn": "386-31-1527"
}, {
  "id": 70,
  "first_name": "Keefe",
  "last_name": "Gutridge",
  "email": "kgutridge1x@bigcartel.com",
  "gender": "Male",
  "ip_address": "119.70.154.48",
  "computer_name": "Laptop",
  "operating_system": "Windows",
  "processor": "AMD Ryzen 7",
  "ram": 49,
  "storage_capacity": 3558,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "33-EB-81-B4-2B-2A",
  "antivirus": "Norton",
  "firewall_enabled": false,
  "ssn": "357-12-1115"
}, {
  "id": 71,
  "first_name": "Georgeanne",
  "last_name": "Prestidge",
  "email": "gprestidge1y@shutterfly.com",
  "gender": "Female",
  "ip_address": "50.43.99.246",
  "computer_name": "Server",
  "operating_system": "macOS",
  "processor": "Qualcomm Snapdragon",
  "ram": 47,
  "storage_capacity": 4049,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "90-B7-E7-EE-28-AF",
  "antivirus": "Norton",
  "firewall_enabled": false,
  "ssn": "163-36-9992"
}, {
  "id": 72,
  "first_name": "Shirl",
  "last_name": "Alphonso",
  "email": "salphonso1z@vinaora.com",
  "gender": "Female",
  "ip_address": "211.99.35.60",
  "computer_name": "Laptop",
  "operating_system": "Windows",
  "processor": "Intel Core i5",
  "ram": 26,
  "storage_capacity": 2082,
  "graphics_card": "Intel Iris Xe",
  "mac_address": "AF-41-A8-D9-DD-19",
  "antivirus": "Norton",
  "firewall_enabled": true,
  "ssn": "820-23-4464"
}, {
  "id": 73,
  "first_name": "Eolande",
  "last_name": "Danser",
  "email": "edanser20@de.vu",
  "gender": "Female",
  "ip_address": "22.151.125.30",
  "computer_name": "Desktop",
  "operating_system": "Linux",
  "processor": "Intel Core i5",
  "ram": 29,
  "storage_capacity": 371,
  "graphics_card": "Intel Iris Xe",
  "mac_address": "28-C0-01-05-7B-5A",
  "antivirus": "Windows Defender",
  "firewall_enabled": false,
  "ssn": "696-13-9619"
}, {
  "id": 74,
  "first_name": "Bogart",
  "last_name": "Giberd",
  "email": "bgiberd21@icq.com",
  "gender": "Male",
  "ip_address": "115.19.153.207",
  "computer_name": "Laptop",
  "operating_system": "Linux",
  "processor": "Qualcomm Snapdragon",
  "ram": 14,
  "storage_capacity": 1683,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "C4-AF-15-ED-25-BC",
  "antivirus": "Norton",
  "firewall_enabled": true,
  "ssn": "442-38-7094"
}, {
  "id": 75,
  "first_name": "Temple",
  "last_name": "Clemenceau",
  "email": "tclemenceau22@yellowpages.com",
  "gender": "Male",
  "ip_address": "169.148.205.255",
  "computer_name": "Server",
  "operating_system": "Linux",
  "processor": "Intel Core i5",
  "ram": 52,
  "storage_capacity": 3617,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "4A-F2-04-DF-BC-A0",
  "antivirus": "Windows Defender",
  "firewall_enabled": true,
  "ssn": "771-25-6434"
}, {
  "id": 76,
  "first_name": "Shaughn",
  "last_name": "Brilon",
  "email": "sbrilon23@woothemes.com",
  "gender": "Male",
  "ip_address": "232.178.119.81",
  "computer_name": "Server",
  "operating_system": "macOS",
  "processor": "AMD Ryzen 7",
  "ram": 30,
  "storage_capacity": 874,
  "graphics_card": "Intel Iris Xe",
  "mac_address": "BC-12-AE-9C-75-50",
  "antivirus": "Windows Defender",
  "firewall_enabled": true,
  "ssn": "636-63-7860"
}, {
  "id": 77,
  "first_name": "Chaunce",
  "last_name": "Bonhill",
  "email": "cbonhill24@youtube.com",
  "gender": "Male",
  "ip_address": "48.178.60.193",
  "computer_name": "Laptop",
  "operating_system": "macOS",
  "processor": "AMD Ryzen 7",
  "ram": 29,
  "storage_capacity": 3753,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "E1-F8-7A-9A-8C-1B",
  "antivirus": "McAfee",
  "firewall_enabled": true,
  "ssn": "330-24-5309"
}, {
  "id": 78,
  "first_name": "Nomi",
  "last_name": "Harriskine",
  "email": "nharriskine25@oracle.com",
  "gender": "Female",
  "ip_address": "79.69.126.98",
  "computer_name": "Desktop",
  "operating_system": "Linux",
  "processor": "AMD Ryzen 7",
  "ram": 26,
  "storage_capacity": 823,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "6C-28-0D-D3-5F-49",
  "antivirus": "Windows Defender",
  "firewall_enabled": true,
  "ssn": "506-42-2689"
}, {
  "id": 79,
  "first_name": "Aylmer",
  "last_name": "Garrould",
  "email": "agarrould26@netlog.com",
  "gender": "Male",
  "ip_address": "0.149.58.58",
  "computer_name": "Laptop",
  "operating_system": "macOS",
  "processor": "AMD Ryzen 7",
  "ram": 61,
  "storage_capacity": 1822,
  "graphics_card": "NVIDIA GeForce RTX 3080",
  "mac_address": "D8-E1-C3-D6-81-66",
  "antivirus": "McAfee",
  "firewall_enabled": true,
  "ssn": "241-11-1753"
}, {
  "id": 80,
  "first_name": "Inigo",
  "last_name": "Rosenkranc",
  "email": "irosenkranc27@chronoengine.com",
  "gender": "Male",
  "ip_address": "192.178.108.238",
  "computer_name": "Laptop",
  "operating_system": "Windows",
  "processor": "Intel Core i5",
  "ram": 8,
  "storage_capacity": 4085,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "94-59-1D-FB-51-8A",
  "antivirus": "Norton",
  "firewall_enabled": false,
  "ssn": "235-68-8754"
}, {
  "id": 81,
  "first_name": "Zachariah",
  "last_name": "Clogg",
  "email": "zclogg28@accuweather.com",
  "gender": "Male",
  "ip_address": "21.165.184.146",
  "computer_name": "Desktop",
  "operating_system": "macOS",
  "processor": "AMD Ryzen 7",
  "ram": 39,
  "storage_capacity": 1006,
  "graphics_card": "Intel Iris Xe",
  "mac_address": "EF-0A-FF-21-47-4E",
  "antivirus": "McAfee",
  "firewall_enabled": true,
  "ssn": "226-34-7617"
}, {
  "id": 82,
  "first_name": "Jerald",
  "last_name": "Geertz",
  "email": "jgeertz29@fda.gov",
  "gender": "Male",
  "ip_address": "238.59.213.144",
  "computer_name": "Laptop",
  "operating_system": "macOS",
  "processor": "Intel Core i5",
  "ram": 18,
  "storage_capacity": 2790,
  "graphics_card": "Intel Iris Xe",
  "mac_address": "DA-44-A3-AB-64-A2",
  "antivirus": "McAfee",
  "firewall_enabled": false,
  "ssn": "260-58-9451"
}, {
  "id": 83,
  "first_name": "Polly",
  "last_name": "Lofting",
  "email": "plofting2a@shop-pro.jp",
  "gender": "Female",
  "ip_address": "121.200.202.170",
  "computer_name": "Desktop",
  "operating_system": "Windows",
  "processor": "AMD Ryzen 7",
  "ram": 48,
  "storage_capacity": 926,
  "graphics_card": "Intel Iris Xe",
  "mac_address": "78-FA-9F-78-61-16",
  "antivirus": "Windows Defender",
  "firewall_enabled": false,
  "ssn": "133-98-9867"
}, {
  "id": 84,
  "first_name": "Cheston",
  "last_name": "Izhak",
  "email": "cizhak2b@utexas.edu",
  "gender": "Male",
  "ip_address": "32.112.44.146",
  "computer_name": "Desktop",
  "operating_system": "Linux",
  "processor": "Qualcomm Snapdragon",
  "ram": 15,
  "storage_capacity": 2737,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "E6-01-ED-5B-7D-33",
  "antivirus": "Norton",
  "firewall_enabled": true,
  "ssn": "336-08-8162"
}, {
  "id": 85,
  "first_name": "Cyril",
  "last_name": "Cleaver",
  "email": "ccleaver2c@instagram.com",
  "gender": "Agender",
  "ip_address": "129.203.76.238",
  "computer_name": "Server",
  "operating_system": "Linux",
  "processor": "Qualcomm Snapdragon",
  "ram": 46,
  "storage_capacity": 2212,
  "graphics_card": "NVIDIA GeForce RTX 3080",
  "mac_address": "03-56-E5-92-F7-BC",
  "antivirus": "McAfee",
  "firewall_enabled": false,
  "ssn": "160-30-8278"
}, {
  "id": 86,
  "first_name": "Olly",
  "last_name": "Jacobson",
  "email": "ojacobson2d@blinklist.com",
  "gender": "Male",
  "ip_address": "63.56.91.179",
  "computer_name": "Laptop",
  "operating_system": "Linux",
  "processor": "AMD Ryzen 7",
  "ram": 18,
  "storage_capacity": 661,
  "graphics_card": "NVIDIA GeForce RTX 3080",
  "mac_address": "56-38-F3-3F-E3-04",
  "antivirus": "Windows Defender",
  "firewall_enabled": false,
  "ssn": "546-93-7437"
}, {
  "id": 87,
  "first_name": "Obed",
  "last_name": "McLean",
  "email": "omclean2e@51.la",
  "gender": "Male",
  "ip_address": "58.55.123.230",
  "computer_name": "Desktop",
  "operating_system": "Linux",
  "processor": "Qualcomm Snapdragon",
  "ram": 34,
  "storage_capacity": 2768,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "5D-7D-3C-87-B3-56",
  "antivirus": "McAfee",
  "firewall_enabled": true,
  "ssn": "817-04-1130"
}, {
  "id": 88,
  "first_name": "Ileane",
  "last_name": "Niblock",
  "email": "iniblock2f@mac.com",
  "gender": "Female",
  "ip_address": "92.246.61.236",
  "computer_name": "Laptop",
  "operating_system": "Windows",
  "processor": "Qualcomm Snapdragon",
  "ram": 38,
  "storage_capacity": 4024,
  "graphics_card": "Intel Iris Xe",
  "mac_address": "09-68-65-D1-4F-21",
  "antivirus": "Norton",
  "firewall_enabled": false,
  "ssn": "508-54-6865"
}, {
  "id": 89,
  "first_name": "Jannel",
  "last_name": "Machans",
  "email": "jmachans2g@woothemes.com",
  "gender": "Female",
  "ip_address": "129.206.253.29",
  "computer_name": "Laptop",
  "operating_system": "Linux",
  "processor": "AMD Ryzen 7",
  "ram": 52,
  "storage_capacity": 1518,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "C2-B3-ED-01-35-F2",
  "antivirus": "McAfee",
  "firewall_enabled": false,
  "ssn": "796-81-8089"
}, {
  "id": 90,
  "first_name": "Justinn",
  "last_name": "Brayford",
  "email": "jbrayford2h@icio.us",
  "gender": "Female",
  "ip_address": "175.168.126.221",
  "computer_name": "Laptop",
  "operating_system": "Windows",
  "processor": "Intel Core i5",
  "ram": 37,
  "storage_capacity": 300,
  "graphics_card": "NVIDIA GeForce RTX 3080",
  "mac_address": "88-D3-10-FC-FB-5A",
  "antivirus": "Norton",
  "firewall_enabled": false,
  "ssn": "880-11-8806"
}, {
  "id": 91,
  "first_name": "Charley",
  "last_name": "Tomaskunas",
  "email": "ctomaskunas2i@techcrunch.com",
  "gender": "Male",
  "ip_address": "59.194.215.130",
  "computer_name": "Laptop",
  "operating_system": "Windows",
  "processor": "Qualcomm Snapdragon",
  "ram": 34,
  "storage_capacity": 2725,
  "graphics_card": "Intel Iris Xe",
  "mac_address": "5C-19-63-76-98-17",
  "antivirus": "Norton",
  "firewall_enabled": true,
  "ssn": "325-80-8543"
}, {
  "id": 92,
  "first_name": "Margit",
  "last_name": "Balchin",
  "email": "mbalchin2j@epa.gov",
  "gender": "Female",
  "ip_address": "236.52.166.20",
  "computer_name": "Desktop",
  "operating_system": "Linux",
  "processor": "AMD Ryzen 7",
  "ram": 63,
  "storage_capacity": 2336,
  "graphics_card": "NVIDIA GeForce RTX 3080",
  "mac_address": "29-8E-01-FC-71-FE",
  "antivirus": "McAfee",
  "firewall_enabled": true,
  "ssn": "821-04-5492"
}, {
  "id": 93,
  "first_name": "Steffi",
  "last_name": "Tattersdill",
  "email": "stattersdill2k@whitehouse.gov",
  "gender": "Female",
  "ip_address": "78.176.93.23",
  "computer_name": "Laptop",
  "operating_system": "Linux",
  "processor": "Intel Core i5",
  "ram": 47,
  "storage_capacity": 3067,
  "graphics_card": "Intel Iris Xe",
  "mac_address": "54-17-68-C9-16-5C",
  "antivirus": "McAfee",
  "firewall_enabled": true,
  "ssn": "653-45-5170"
}, {
  "id": 94,
  "first_name": "Tove",
  "last_name": "Muscroft",
  "email": "tmuscroft2l@newyorker.com",
  "gender": "Female",
  "ip_address": "100.197.211.12",
  "computer_name": "Desktop",
  "operating_system": "macOS",
  "processor": "AMD Ryzen 7",
  "ram": 37,
  "storage_capacity": 1952,
  "graphics_card": "NVIDIA GeForce RTX 3080",
  "mac_address": "56-D9-5C-E9-57-0C",
  "antivirus": "Norton",
  "firewall_enabled": false,
  "ssn": "817-16-4126"
}, {
  "id": 95,
  "first_name": "Gabriella",
  "last_name": "Lantuffe",
  "email": "glantuffe2m@weather.com",
  "gender": "Female",
  "ip_address": "131.97.65.190",
  "computer_name": "Desktop",
  "operating_system": "macOS",
  "processor": "AMD Ryzen 7",
  "ram": 29,
  "storage_capacity": 3049,
  "graphics_card": "Intel Iris Xe",
  "mac_address": "15-D9-2F-29-2C-94",
  "antivirus": "McAfee",
  "firewall_enabled": false,
  "ssn": "238-69-3891"
}, {
  "id": 96,
  "first_name": "Juliet",
  "last_name": "Bartak",
  "email": "jbartak2n@oracle.com",
  "gender": "Female",
  "ip_address": "68.167.17.135",
  "computer_name": "Server",
  "operating_system": "Windows",
  "processor": "AMD Ryzen 7",
  "ram": 15,
  "storage_capacity": 2641,
  "graphics_card": "NVIDIA GeForce RTX 3080",
  "mac_address": "3B-8D-0F-DD-D0-8C",
  "antivirus": "Norton",
  "firewall_enabled": true,
  "ssn": "768-81-8856"
}, {
  "id": 97,
  "first_name": "Walliw",
  "last_name": "Folomkin",
  "email": "wfolomkin2o@pagesperso-orange.fr",
  "gender": "Female",
  "ip_address": "114.201.184.163",
  "computer_name": "Server",
  "operating_system": "Windows",
  "processor": "Intel Core i5",
  "ram": 53,
  "storage_capacity": 1483,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "06-D0-FD-FD-1B-A1",
  "antivirus": "Norton",
  "firewall_enabled": false,
  "ssn": "541-65-7259"
}, {
  "id": 98,
  "first_name": "Adelbert",
  "last_name": "Sallnow",
  "email": "asallnow2p@smugmug.com",
  "gender": "Male",
  "ip_address": "59.72.227.191",
  "computer_name": "Laptop",
  "operating_system": "Windows",
  "processor": "Qualcomm Snapdragon",
  "ram": 10,
  "storage_capacity": 277,
  "graphics_card": "NVIDIA GeForce RTX 3080",
  "mac_address": "B5-DC-20-FC-0F-C7",
  "antivirus": "Norton",
  "firewall_enabled": true,
  "ssn": "456-74-9969"
}, {
  "id": 99,
  "first_name": "Ibbie",
  "last_name": "Jeal",
  "email": "ijeal2q@pagesperso-orange.fr",
  "gender": "Bigender",
  "ip_address": "47.195.7.186",
  "computer_name": "Server",
  "operating_system": "Linux",
  "processor": "AMD Ryzen 7",
  "ram": 6,
  "storage_capacity": 1448,
  "graphics_card": "NVIDIA GeForce RTX 3080",
  "mac_address": "6A-F7-F7-6C-7C-B6",
  "antivirus": "McAfee",
  "firewall_enabled": false,
  "ssn": "214-37-9904"
}, {
  "id": 100,
  "first_name": "Blancha",
  "last_name": "Eykelhof",
  "email": "beykelhof2r@google.com",
  "gender": "Female",
  "ip_address": "98.251.196.155",
  "computer_name": "Server",
  "operating_system": "Windows",
  "processor": "Intel Core i5",
  "ram": 41,
  "storage_capacity": 1290,
  "graphics_card": "AMD Radeon RX 6800 XT",
  "mac_address": "86-C0-48-A7-E0-F0",
  "antivirus": "McAfee",
  "firewall_enabled": true,
  "ssn": "895-27-9765"
}]